library(gdata)
library(zoo)
library(testthat)
library(readr)
#library(reshape2)
library(maptools)
library(ggplot2)
library(rgdal)
library(lubridate)
library(stringr)
library(foreign)
#library(reshape)
library(jsonlite)
library(xtable)
library(dplyr)
library(readxl)
library(tidyr)
library(rgeos)
library(maps)
library(maptools)
library(sp)
library(tidyr)
options(stringsAsFactors = FALSE)

#library(Rcompression)
theme_set(theme_bw())