name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Clean Data for HoyoDeCrimen
      env:
        DOCKER_USERNAME: ${{  secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{  secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u="$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        docker pull diegovalle/docker-rstanarm:latest
        docker run --entrypoint /bin/sh -e CI="true" -v "$GITHUB_WORKSPACE":/hoyodecrimen diegovalle/docker-rstanarm -c "cd /hoyodecrimen  && Rscript run-all.R"
    - name: Collect artifacts if analysis failed
      env:
        ACCOUNT_ID: ${{  secrets.ACCOUNT_ID }}
        APPLICATION_KEY: ${{  secrets.APPLICATION_KEY }}
        BUCKET_ID: ${{  secrets.BUCKET_ID }}
      if: failure()
      run: |
        zip hoyodecrimen-clean.zip "$GITHUB_WORKSPACE"/clean-data/*.RData "$GITHUB_WORKSPACE"/graphs/* && "$GITHUB_WORKSPACE"/upload_to_b2.sh hoyodecrimen-clean.zip
    - name: upload charts and RData files
      env:
        ACCOUNT_ID: ${{  secrets.ACCOUNT_ID }}
        APPLICATION_KEY: ${{  secrets.APPLICATION_KEY }}
        BUCKET_ID: ${{  secrets.BUCKET_ID }}
      run: |
        zip hoyodecrimen-clean.zip "$GITHUB_WORKSPACE"/clean-data/*.RData "$GITHUB_WORKSPACE"/graphs/* && "$GITHUB_WORKSPACE"/upload_to_b2.sh hoyodecrimen-clean.zip
    - name: upload csv artifacts
      env:
        ACCOUNT_ID: ${{  secrets.ACCOUNT_ID_HOYODECRIMEN }}
        APPLICATION_KEY: ${{  secrets.APPLICATION_KEY_HOYODECRIMEN }}
        BUCKET_ID: ${{  secrets.BUCKET_ID_HOYODECRIMEN }}
      run: |
        echo "Uploading to B2"
        zip crime-lat-long-pgj.csv.zip "$GITHUB_WORKSPACE"/clean-data/crime-lat-long-pgj.csv && "$GITHUB_WORKSPACE"/upload_to_b2.sh crime-lat-long-pgj.csv.zip
        zip cuadrantes-pgj.csv.zip "$GITHUB_WORKSPACE"/clean-data/cuadrantes-pgj.csv && "$GITHUB_WORKSPACE"/upload_to_b2.sh cuadrantes-pgj.csv.zip
        zip pgj.csv.zip "$GITHUB_WORKSPACE"/clean-data/pgj.csv && "$GITHUB_WORKSPACE"/upload_to_b2.sh pgj.csv.zip
    - name: Invalidate stale cache
      run: |
        curl -o /dev/null -v https://data.diegovalle.net/hoyodecrimen/crime-lat-long-pgj.csv.zip -H "$CACHE_INVALIDATE_HEADER:true"
        curl -o /dev/null -v https://data.diegovalle.net/hoyodecrimen/cuadrantes-pgj.csv.zip -H "$CACHE_INVALIDATE_HEADER:true"
        curl -o /dev/null -v https://data.diegovalle.net/hoyodecrimen/pgj.csv.zip -H "$CACHE_INVALIDATE_HEADER:true"
