name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Clean Data for HoyoDeCrimen
      run: |
        docker pull diegovalle/docker-rstanarm:latest
        docker run --entrypoint /bin/sh -e CI="true" -v "$GITHUB_WORKSPACE":/hoyodecrimen diegovalle/docker-rstanarm -c "cd /hoyodecrimen  && Rscript run-all.R"
    - name: upload artifacts
      env:
        ACCOUNT_ID: ${{  secrets.ACCOUNT_ID }}
        APPLICATION_KEY: ${{  secrets.APPLICATION_KEY }}
        BUCKET_ID: ${{  secrets.BUCKET_ID }}
      run: zip hoyodecrimen-clean.zip $GITHUB_WORKSPACE/output/* $GITHUB_WORKSPACE/graphs/* && $GITHUB_WORKSPACE/upload_to_b2.sh hoyodecrimen-clean.zip
